### ISSUE TITLE
How can I get the access key?

### ISSUE THREAD

**Issue by seualphagit** [jeremypedersen/deepracer-deepstats#1]
I got some problem. I was blocked here:
Configuring IAM Permissions (Optional)
If you plan to automatically fetch log data using the DeepRacer API, this notebook will need to have permissions to access the DeepRacer services, and possibly additional services like S3.
If you are using your local machine, make sure you have the AWS CLI installed and have a valid Access Key with the required permissions.

=> But I can' t get the access key at the console. My website is:
![image](https://github.com/jeremypedersen/deepracer-deepstats/assets/34829754/e5fb3d58-c07a-4bc1-b6f3-360729becf4d)

I also get the same problem when I try to install DeepRacer for Cloud at local machine
![image](https://github.com/jeremypedersen/deepracer-deepstats/assets/34829754/613403b4-0409-4a60-af84-2faa852c4971)

Could you help me?

**Comment by jeremypedersen** [comment]
Hi! I see you have two questions: 

1. How can I install and use DeepRacer for Cloud Locally? 
2. How can I use the Jupyter Notebook if I don't have an Access Key ?

**Question 1 is outside the scope of this project...DeepRacer for Cloud is maintained by other people**. You can check the [DeepRacer for Cloud installation instructions](https://aws-deepracer-community.github.io/deepracer-for-cloud/installation.html) for more details. Because your issue is with setting up MinIO, [this page from the MinIO documentation](https://min.io/docs/minio/linux/integrations/aws-cli-with-minio.html) might be helpful too. It explains how to use MinIO with the AWS CLI without an AWS Access Key.

For Question 2, **you don't actually need an AWS Access Key to use the notebook**. Instead, you can download your model and log files *directly from the console* and then run local analysis on them. Here's how: 

## Step 1: Download your logs

Use the "Download logs" button to download a copy of your log files.

<img width="720" alt="image" src="https://github.com/jeremypedersen/deepracer-deepstats/assets/42971949/7a4f1d0a-47a8-4bdd-ba03-ca2b73a97ad4">

## Step 2: Download your model checkpoint:

Use the "Download physical car model" option under the "Actions" menu to download a copy of your model file. 

<img width="720" alt="image" src="https://github.com/jeremypedersen/deepracer-deepstats/assets/42971949/f8cec316-f885-42ac-8f43-b0c07223bb05">

## Step 3: Move your log and model files to the `local_model_files` directory

Move both your log and model files to the `local_model_files` directory. They will be in `.tar.gz` format. **Do not extract them**, the Jupyter Notebook will do this step for you.

<img width="670" alt="image" src="https://github.com/jeremypedersen/deepracer-deepstats/assets/42971949/597a06f7-5d80-4808-8f7b-dd01dec148a3">

## Step 4: Update the file paths in the Jupyter notebook

Update the "Fetch Logs" section of the Jupyter notebook to point to your log and model files. 

<img width="776" alt="image" src="https://github.com/jeremypedersen/deepracer-deepstats/assets/42971949/ca00e088-4f1b-4a31-9fc1-2d7241963c05">

<img width="776" alt="image" src="https://github.com/jeremypedersen/deepracer-deepstats/assets/42971949/a93fa0c2-cc49-4891-9b5c-10acc8751752">

**Once you have done this, you should be able to run the notebook without needing an AWS Access Key.** The notebook will simply unpack your local log files and use them to run the analysis.
